/** Build a printable / downloadable HTML offer letter document. */
export function buildOfferDocumentHtml(params: {
  title: string;
  contentHtml: string;
  candidateName?: string;
  companyName?: string;
  status?: string;
  sentAt?: string | Date | null;
}) {
  const sentLabel = params.sentAt
    ? new Date(params.sentAt).toLocaleString()
    : "—";
  const safeTitle = escapeHtml(params.title);
  const company = escapeHtml(params.companyName || "HireFlow");
  const candidate = escapeHtml(params.candidateName || "Candidate");
  const status = escapeHtml(params.status || "sent");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${safeTitle}</title>
  <style>
    :root { color-scheme: light; }
    body {
      font-family: Georgia, "Times New Roman", serif;
      margin: 0;
      background: #f4f6fb;
      color: #111827;
    }
    .toolbar {
      position: sticky;
      top: 0;
      display: flex;
      gap: 8px;
      align-items: center;
      justify-content: flex-end;
      padding: 12px 20px;
      background: #111827;
      color: #fff;
    }
    .toolbar button {
      border: 0;
      border-radius: 8px;
      padding: 8px 14px;
      cursor: pointer;
      font-weight: 600;
      background: #6366f1;
      color: #fff;
    }
    .sheet {
      max-width: 800px;
      margin: 24px auto;
      background: #fff;
      padding: 48px;
      border-radius: 16px;
      box-shadow: 0 10px 40px rgba(15, 23, 42, 0.08);
    }
    .meta {
      font-family: Inter, system-ui, sans-serif;
      font-size: 12px;
      color: #6b7280;
      margin-bottom: 24px;
    }
    h1 {
      font-size: 28px;
      margin: 0 0 8px;
    }
    .content { line-height: 1.6; font-size: 15px; }
    .content h2 { font-size: 20px; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-family: Inter, system-ui, sans-serif;
      font-size: 12px;
      color: #9ca3af;
    }
    @media print {
      body { background: #fff; }
      .toolbar { display: none; }
      .sheet { box-shadow: none; margin: 0; border-radius: 0; padding: 0; }
    }
  </style>
</head>
<body>
  <div class="toolbar">
    <span style="margin-right:auto;font:600 13px Inter,system-ui,sans-serif">HireFlow Offer</span>
    <button onclick="window.print()">Print / Save as PDF</button>
  </div>
  <article class="sheet">
    <div class="meta">
      <div><strong>Company:</strong> ${company}</div>
      <div><strong>Candidate:</strong> ${candidate}</div>
      <div><strong>Status:</strong> ${status}</div>
      <div><strong>Sent:</strong> ${escapeHtml(sentLabel)}</div>
    </div>
    <h1>${safeTitle}</h1>
    <div class="content">${params.contentHtml}</div>
    <div class="footer">Generated by HireFlow · Use Print → Save as PDF to download a PDF copy.</div>
  </article>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
