services:
  mongo:
    image: mongo:7
    container_name: hireflow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: recruiter-system
    volumes:
      - hireflow_mongo_data:/data/db

volumes:
  hireflow_mongo_data:
